### ISSUE TITLE
formatting incorrect syntax with stylish-haskell dumps error message into buffer

### ISSUE THREAD

**Issue by Alok** [sbdchd/neoformat#41]
See line 30 of [this gist](https://gist.github.com/90bd979dc6496dfe0ddb72cdd799c58b), which needs to be indented. Running neoformat with stylish-haskell puts an error message at line 1. I thought neoformat ignored all of STDERR? if not, STDERR for this formatted may need to be redirected (again) to /dev/null.

**Comment by sbdchd** [comment]
`system()` outputs both stdout and stderr together, previously with `job_control()`, Neoformat was able to handle stderr and stdout separately.

Neoformat relies on formatters outputting an error status code when they output to stderr.

```viml
let cmd = "echo 'test' >> /dev/stderr"

let output = system(cmd)
if !v:shell_error
    echom output
endif
" outputs: test, since there was no error code given
```

It might make sense to add `2>/dev/null` as a base arg before running all formatters, but I think that might not be 100% portable.

I think for now, `2>/dev/null` should just be added back to `stylish-haskell` definition, since it apparently doesn't always send an error code when outputting to stderr.
