### ISSUE TITLE
Add stdout option

### ISSUE THREAD

**Issue by nilsboy** [sbdchd/neoformat#42]
I'm trying to get eslint to work with neoformat. Eslint does nether support stdin for formatting nor does it print the result on stdout. The file to be formatted is instead changed in place.

Could you add a stdout option which would ignore the stdout of the formatter and just use the changed temp file?

Thank you.

**Comment by sbdchd** [comment]
https://github.com/sbdchd/neoformat#config-optional

I think [`replace: 1`][1] should do the trick.
The description of it isn't that great, but it replaces the `tmp` file instead of using the stdout of the formatter.

Something like the following should work:

```viml
let g:neoformat_javascript_eslint {
        \ 'exe': 'eslint',
        \ 'args': ['--fix'],
        \ 'replace': 1,
        \ }

let g:neoformat_enabled_javascript = ['eslint']
```



[1]: https://github.com/sbdchd/neoformat#config-optional

**Comment by Alok** [comment]
`eslint` appears to have a `--stdin` flag which seems to work, from its description. You should test it. If it works, then you could do this:

```vim
let g:neoformat_javascript_eslint {
        \ 'exe': 'eslint',
        \ 'args': ['--fix', '--stdin '],
        \ 'stdin': 1,
        \ }
```

**Comment by sbdchd** [comment]
For some reason `eslint` doesn't like to mix `--fix` and `--stdin`.

```bash
echo "const x = 'test'" | eslint --fix --stdin
# The --fix option is not available for piped-in code.
```

**Comment by nilsboy** [comment]
Yes 'replace': 1 works.
Thank you!
